package:
  name: pytestpackage
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'notfound') }}

source:
  path: /__w/anaconda-package-cd-test/anaconda-package-cd-test

build:
  number: 0

requirements:
  host:
    - python 3.7
  run:
    - python 3.7
    - pyyaml

#test:
#  imports:
#    - ppppppytestpackage
